const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openFile: () => ipcRenderer.invoke('open-file'),
  saveReview: (review) => ipcRenderer.invoke('save-review', review),
  saveDraft: (data) => ipcRenderer.invoke('save-draft', data),
  loadDraft: (filePath) => ipcRenderer.invoke('load-draft', filePath),
  deleteDraft: (filePath) => ipcRenderer.invoke('delete-draft', filePath),
  getConfig: () => ipcRenderer.invoke('get-config'),
  savePreferences: (prefs) => ipcRenderer.invoke('save-preferences', prefs),
  exportMarkdown: (data) => ipcRenderer.invoke('export-markdown', data),
  saveImage: (data) => ipcRenderer.invoke('save-image', data),
  loadPr: (prNumber) => ipcRenderer.invoke('load-pr', prNumber),
  listPrs: () => ipcRenderer.invoke('list-prs'),
  openPrNewWindow: (prNumber) => ipcRenderer.invoke('open-pr-new-window', prNumber),
  getPrCommits: (prNumber) => ipcRenderer.invoke('get-pr-commits', prNumber),
  getFileBlame: (data) => ipcRenderer.invoke('get-file-blame', data),
  submitGitHubReview: (data) => ipcRenderer.invoke('submit-github-review', data),
  openFileInEditor: (data) => ipcRenderer.invoke('open-file-in-editor', data),
  getAgentRules: () => ipcRenderer.invoke('get-agent-rules'),
  proposeRules: (data) => ipcRenderer.invoke('propose-rules', data),
  saveAgentRules: (data) => ipcRenderer.invoke('save-agent-rules', data),
  deletePrFiles: (prNumber) => ipcRenderer.invoke('delete-pr-files', prNumber),
  getNextPr: (prNumber) => ipcRenderer.invoke('get-next-pr', prNumber),
  listRepos: () => ipcRenderer.invoke('list-repos'),
  saveRepos: (repos) => ipcRenderer.invoke('save-repos', repos),
  listAllPrs: (data) => ipcRenderer.invoke('list-all-prs', data),
  onLoadDiff: (callback) => ipcRenderer.on('load-diff', (event, data) => callback(data)),
  onTriggerOpenFile: (callback) => ipcRenderer.on('trigger-open-file', () => callback()),
  onOpenPreferences: (callback) => ipcRenderer.on('open-preferences', () => callback()),
  getCollaborators: () => ipcRenderer.invoke('get-collaborators'),
  autoFixWithAi: (data) => ipcRenderer.invoke('auto-fix-with-ai', data),
  processVoiceCommand: (data) => ipcRenderer.invoke('process-voice-command', data),
  exportJson: (data) => ipcRenderer.invoke('export-json', data),
  onExportMarkdown: (callback) => ipcRenderer.on('export-markdown', () => callback()),
  onExportJson: (callback) => ipcRenderer.on('export-json', () => callback()),
  downloadGithubImages: (data) => ipcRenderer.invoke('download-github-images', data),
  checkBinaries: () => ipcRenderer.invoke('check-binaries'),
  autoDetectAgent: () => ipcRenderer.invoke('auto-detect-agent')
});
