const { contextBridge, ipcRenderer } = require('electron');

// Expose highlight.js globally for diff2html syntax highlighting
try {
  const hljs = require('highlight.js');
  contextBridge.exposeInMainWorld('hljs', hljs);
} catch (err) {
  console.warn('[preload] highlight.js not available:', err.message);
}

contextBridge.exposeInMainWorld('electronAPI', {
  rendererLog: (level, ...args) => ipcRenderer.invoke('renderer-log', level, ...args),
  checkoutMaster: (repoKey) => ipcRenderer.invoke('checkout-master', { repoKey }),
  openFile: () => ipcRenderer.invoke('open-file'),
  saveReview: (review) => ipcRenderer.invoke('save-review', review),
  saveDraft: (data) => ipcRenderer.invoke('save-draft', data),
  loadDraft: (filePath) => ipcRenderer.invoke('load-draft', filePath),
  deleteDraft: (filePath) => ipcRenderer.invoke('delete-draft', filePath),
  savePrDraft: (data) => ipcRenderer.invoke('save-pr-draft', data),
  loadPrDraft: (prNumber) => ipcRenderer.invoke('load-pr-draft', prNumber),
  deletePrDraft: (prNumber) => ipcRenderer.invoke('delete-pr-draft', prNumber),
  getConfig: () => ipcRenderer.invoke('get-config'),
  savePreferences: (prefs) => ipcRenderer.invoke('save-preferences', prefs),
  exportMarkdown: (data) => ipcRenderer.invoke('export-markdown', data),
  saveImage: (data) => ipcRenderer.invoke('save-image', data),
  loadPr: (prNumber) => ipcRenderer.invoke('load-pr', prNumber),
  getPrInfo: (data) => ipcRenderer.invoke('get-pr-info', data),
  prefetchPr: (data) => ipcRenderer.invoke('prefetch-pr', data),
  getPrefetchedPr: (data) => ipcRenderer.invoke('get-prefetched-pr', data),
  listPrs: () => ipcRenderer.invoke('list-prs'),
  openPrNewWindow: (prNumber) => ipcRenderer.invoke('open-pr-new-window', prNumber),
  getPrCommits: (prNumber, baseSha) => ipcRenderer.invoke('get-pr-commits', prNumber, baseSha),
  getFileBlame: (data) => ipcRenderer.invoke('get-file-blame', data),
  submitGitHubReview: (data) => ipcRenderer.invoke('submit-github-review', data),
  openFileInEditor: (data) => ipcRenderer.invoke('open-file-in-editor', data),
  getAgentRules: () => ipcRenderer.invoke('get-agent-rules'),
  proposeRules: (data) => ipcRenderer.invoke('propose-rules', data),
  aiChat: (data) => ipcRenderer.invoke('ai-chat', data),
  onAiChatStream: (callback) => ipcRenderer.on('ai-chat-stream', (event, data) => callback(data)),
  removeAiChatStreamListener: (callback) => ipcRenderer.removeListener('ai-chat-stream', callback),
  saveAgentRules: (data) => ipcRenderer.invoke('save-agent-rules', data),
  deletePrFiles: (prNumber) => ipcRenderer.invoke('delete-pr-files', prNumber),
  getSavedAgentRules: () => ipcRenderer.invoke('get-saved-agent-rules'),
  getNextPr: (prNumber) => ipcRenderer.invoke('get-next-pr', prNumber),
  listRepos: () => ipcRenderer.invoke('list-repos'),
  saveRepos: (repos) => ipcRenderer.invoke('save-repos', repos),
  listAllPrs: (data) => ipcRenderer.invoke('list-all-prs', data),
  onLoadDiff: (callback) => ipcRenderer.on('load-diff', (event, data) => callback(data)),
  onTriggerOpenFile: (callback) => ipcRenderer.on('trigger-open-file', () => callback()),
  onOpenPreferences: (callback) => ipcRenderer.on('open-preferences', () => callback()),
  onOpenShortcuts: (callback) => ipcRenderer.on('open-shortcuts', () => callback()),
  onOpenReviewHistory: (callback) => ipcRenderer.on('open-review-history', () => callback()),
  onCheckUpdateMenu: (callback) => ipcRenderer.on('check-update-menu', () => callback()),
  getCollaborators: (repoKey) => ipcRenderer.invoke('get-collaborators', repoKey),
  getReviewComments: (data) => ipcRenderer.invoke('get-review-comments', data),
  autoFixWithAi: (data) => ipcRenderer.invoke('auto-fix-with-ai', data),
  processVoiceCommand: (data) => ipcRenderer.invoke('process-voice-command', data),
  exportJson: (data) => ipcRenderer.invoke('export-json', data),
  onExportMarkdown: (callback) => ipcRenderer.on('export-markdown', () => callback()),
  onExportJson: (callback) => ipcRenderer.on('export-json', () => callback()),
  downloadGithubImages: (data) => ipcRenderer.invoke('download-github-images', data),
  checkBinaries: () => ipcRenderer.invoke('check-binaries'),
  autoDetectAgent: () => ipcRenderer.invoke('auto-detect-agent'),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  applyUpdate: () => ipcRenderer.invoke('apply-update'),
  setAutoUpdate: (enabled) => ipcRenderer.invoke('set-auto-update', enabled),
  closePr: (data) => ipcRenderer.invoke('close-pr', data),
  expandDiffContext: (data) => ipcRenderer.invoke('expand-diff-context', data),
  openExternal: (url) => ipcRenderer.invoke('open-external', url)
});
